//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWMData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFlowmeter
    {
        public int fId { get; set; }
        public int fSerialNo { get; set; }
        public System.DateTime fDateTime { get; set; }
        public double fDepth { get; set; }
        public double fVelocity { get; set; }
        public double fTemperature { get; set; }
        public double fQuality { get; set; }
        public double fFlow { get; set; }
        public string fDate { get; set; }
        public string fTime { get; set; }
    }
}
